---
- name: convert host_collection groups to patch schedules
  hosts: all

  tasks:
    - name: show groups
      debug:
        var: groups

    - name: Process each group
      debug:
        msg: "Processing group {{ item }}"
      loop: "{{ groups.keys() | difference(['all', 'ungrouped']) }}"