---
- name: convert host_collection groups to patch schedules
  hosts: localhost

  tasks:
    - name: show groups
      debug:
        var: groups

    - name: Show Patch Date
      debug:
        msg: "{{ item | extract_patch_date_from_host_collection}}"
      loop: "{{ groups.keys() | difference(['all', 'ungrouped']) }}"

    - name: build patch schedules
      ansible.controller.schedule:
        name: "sc - patch {{ item }}"
        state: present
        unified_job_template: "SC - Patching"
        limit: "{{ item }}"
        rrule: "{{ query('ansible.controller.schedule_rrule', 'none', start_date=item | extract_patch_date_from_host_collection) }}"
      loop: "{{ groups.keys() | difference(['all', 'ungrouped']) }}"