---
- name: convert host_collection groups to patch schedules
  hosts: all

  tasks:
    - name: show groups
      debug:
        var: groups

    - name: Show Patch Date
      debug:
        msg: "{{ item | extract_patch_date_from_host_collection}}"
      loop: "{{ groups.keys() | difference(['all', 'ungrouped']) }}"